spark.sql.session.timeZone UTC
spark.sql.catalog.threatlake org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.threatlake.type hive
spark.sql.catalog.threatlake.uri thrift://hive-metastore:9083
spark.sql.catalog.threatlake.warehouse s3a://threatlake/warehouse
spark.sql.catalog.threatlake.io-impl org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.threatlake.s3.endpoint http://minio:9000
spark.sql.catalog.threatlake.s3.path-style-access true
spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.access.key minioadmin
spark.hadoop.fs.s3a.secret.key minioadmin
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
